name = "Radish"
author = "qwertron"
link = ""
year = 2022

[formats.standard]
matrix = [["v", "c", "w", "f", "q", "z", "p", "u", "o", "y", "/", "="],
["r", "d", "s", "h", "l", "k", "t", "e", "a", "i", "-"],
["b", "j", "m", "n", "w", ";", "g", "'", ",", "."]]

map = {}
home_row = 1
